### PR TITLE
fixed Issue #255

### PR DESCRIPTION
**Pull request by jackruan99**

### CODE REVIEW

**Comment by rkrishnasanka** [comment]
So I tested out the code, it seems to be giving me the same bug after the first valve
Screen Shot 2021-07-06 at 7 31 29 PM

**Comment by jackruan99** [comment]
It should work now

**Comment by rkrishnasanka** [comment]
@jackruan99 good job with the fix. It seems like its doing the breaks every time now however, the breaks are not correct on angled connections: 
Screen Shot 2021-07-07 at 9 50 41 AM

**Comment by jackruan99** [comment]
fixed inserting valves into angled connections

**Comment by rkrishnasanka** [comment]
Everything seems to be working correctly:
Screen Shot 2021-07-12 at 11 58 12 AM

**Pull request merged**
